name = "anime-master-game-api"
main = "worker/index.ts"
compatibility_date = "2026-06-01"

[[durable_objects.bindings]]
name = "ROOM_OBJECTS"
class_name = "RoomDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomDurableObject"]

[[d1_databases]]
binding = "DB"
database_name = "anime_master_game"
database_id = "bdc89668-68ab-48bd-968b-ebcc40367da2"
migrations_dir = "d1/migrations"

[vars]
ALLOWED_ORIGIN = "https://anime-master-game-v2.pages.dev"
CLOUDINARY_CLOUD_NAME = "dfdfibosf"
CLOUDINARY_FOLDER = "anime-master-game"
CLOUDINARY_EXISTING_IMAGE_LIMIT = "50"

[observability]
enabled = true
head_sampling_rate = 1
